const ShoppingBagDropdownActionTypes = {
    TOGGLE_SHOPPINGBAG_HIDDEN: 'TOGGLE_SHOPPINGBAG_HIDDEN',
    ADD_TO_SHOPPINGBAG: 'ADD_TO_SHOPPINGBAG',
    REMOVE_ITEM_FROM_SHOPPINGBAG: 'REMOVE_ITEM_FROM_SHOPPINGBAG',
    DECREASE_QUANTITY_ITEM: 'DECREASE_QUANTITY_ITEM'
}

export default ShoppingBagDropdownActionTypes;